CC    = ppc-amigaos-gcc
STRIP = ppc-amigaos-strip

TARGET  = sshd
VERSION = 1

OPTIMIZE = -O2
DEBUG    = -gstabs
INCLUDES = -I. -I$(AOS4_SDK_INC) -I${AMISSL_INC} -I${UUID_INC}
WARNINGS = -Wall -Wwrite-strings -Werror -Wsizeof-array-argument -Wno-address-of-packed-member -Wno-deprecated-declarations
DEFINES  = -D__NOLIBBASE__ -DOPENSSL_SYS_AMIGA

CFLAGS  = $(OPTIMIZE) $(DEBUG) $(INCLUDES) $(WARNINGS) $(DEFINES)
LDFLAGS = -static -mcrt=newlib
LIBS    = 

STRIPFLAGS = -R.comment --strip-unneeded-rel-relocs

SRCS := $(shell find . -maxdepth 1 -name '*.c')

OBJS = $(SRCS:.c=.o)

.PHONY: all clean realclean revision 

###########################################################################

all: dist/$(TARGET)

dist/$(TARGET): $(OBJS)
	@mkdir -p dist
	$(CC) $(LDFLAGS) -o $@.debug $^ $(LIBS)
	$(STRIP) $(STRIPFLAGS) -o $@ $@.debug

###########################################################################

revision:
	bumprev -e si $(VERSION) $(TARGET)


###########################################################################

clean:
	rm -rf *.o 

realclean:
	rm -f *.o  $(NAME) *.debug *.map makefile.depend

makefile.depend: ;
	@echo "WARNING: makefile.depend missing. Please run 'make depend'" 

depend:
	@echo "  MK makefile.depend" 
	@echo "  [This may take a minute...]" 
	@echo "# AUTOGENERATED! DO NOT EDIT!!!" >makefile.depend 
	@$(CC) -MM $(patsubst %.o,%.c, $(OBJS)) >>makefile.depend 

## DEPENDENCY INCLUDE #################

-include makefile.depend

###########################################################################

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<
